force-app/main/default/objects/Associate__c/Associate__c.object-meta.xml
<CustomObject>
    <label>Associate</label>
    <nameField>
        <label>Associate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Associate__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Associates</relationshipLabel>
    <relationshipName>Associates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AssociateTeamAssignment_Utility.cls
public class AssociateTeamAssignment_Utility {    
    @InvocableMethod(label='Get Selected Associates By Id' description='Retrieves all associates whose Id is in provided list of Ids.')
    public static List<List<Associate__c>> getSelectedAssociatesById(List<List<String>> nestedAssociateIds) {
        List<List<Associate__c>> retrievedAssociateList = new List<List<Associate__c>>();
        
        List<String> associateIds = nestedAssociateIds[0][0].split('; ');
        
        retrievedAssociateList.add([SELECT Id, Team__c FROM Associate__c WHERE Id IN :associateIds]);
        
        return retrievedAssociateList;
    }
}